# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# SWAGGER
# ===============================
springdoc.swagger-ui.path=/swagger

# ===============================
# DATABASE - PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/taskmanager
spring.datasource.username=postgres
spring.datasource.password=victor2002

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=MnhcO1Z1aZVhULeuhXE/VagNOzVR9uH8a/UeasrVd5E=